// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uudfciytlemkmdmbyfxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1ZGZjaXl0bGVta21kbWJ5ZnhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMzE4NjIsImV4cCI6MjA3MzgwNzg2Mn0.mq6om-QL3rbueOo0aeDAQqdyQKsvt6EIc_V5l9Vp0z4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});